// Test generated by RoostGPT for test NodeUnitTest using AI Type Open AI and AI Model gpt-4

import { describe, beforeAll, test, afterAll, expect } from '@jest/globals';
import mongoose from 'mongoose';

describe("Database Connection", () => {
  beforeAll(async () => {
    jest.setTimeout(10000);
  });

  test("should connect to the database successfully", async () => {
    await mongoose.connect("mongodb://127.0.0.1:27017", {
      dbName: "backend"
    });
    const connectionState = mongoose.connection.readyState;
    expect(connectionState).toBe(1);
  });

  test("should fail to connect to the database", async () => {
    try {
      await mongoose.connect("mongodb://invalid:27017", {
        dbName: "backend"
      });
    } catch (error) {
      expect(error).toBeTruthy();
    }
  });

  afterAll(async () => {
    await mongoose.connection.close();
  });
});
