// Test generated by RoostGPT for test NodeUnitTest using AI Type Open AI and AI Model gpt-4

import express from "express";
import request from "supertest";

describe("Server", () => {
  let server;
  let app;

  beforeAll(() => {
    app = express();
    app.listen(5000, () => {
      console.log("Server is working");
    });

    server = request(app);
  });

  test("should start the server successfully", async () => {
    const response = await server.get("/");

    expect(response.status).toBe(200);
  });

  test("should return 404 for non-existent routes", async () => {
    const response = await server.get("/non-existent-route");

    expect(response.status).toBe(404);
  });

  afterAll(() => {
    app.close();
  });
});
