// Test generated by RoostGPT for test NodeUnitTest using AI Type Open AI and AI Model gpt-4

import express from "express";
import request from "supertest";
import path from "path";
import mongoose from "mongoose";
import cookieParser from "cookie-parser";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";
import { isAuthenticated } from './index';

// Mock Express app
const app = express();
app.use(cookieParser());

// Mock middleware
app.use((req, res, next) => {
  req.user = {
    name: 'Test User'
  };
  next();
});

app.get("/", isAuthenticated, (req, res) => {
  res.status(200).json({
    name: req.user.name
  });
});

describe("GET / - Homepage", () => {
  test("Should return user's name if authenticated", async () => {
    const response = await request(app).get("/");
    expect(response.statusCode).toBe(200);
    expect(response.body).toEqual({
      name: 'Test User'
    });
  });

  test("Should return 401 if not authenticated", async () => {
    // Remove mock middleware
    app._router.stack.pop();

    const response = await request(app).get("/");
    expect(response.statusCode).toBe(401);
  });
});
