// Test generated by RoostGPT for test NodeUnitTest using AI Type Open AI and AI Model gpt-4

import { generateLovePercent } from './features';

describe('Testing generateLovePercent method', () => {
  
  test('Check if it returns a string', () => {
    const result = generateLovePercent();
    expect(typeof result).toBe('string');
  });

  test('Check if it returns a string with a "%" at the end', () => {
    const result = generateLovePercent();
    expect(result[result.length - 1]).toBe('%');
  });

  test('Check if it returns a number between 0 and 100', () => {
    const result = generateLovePercent();
    const number = parseInt(result.slice(0, -1));
    expect(number).toBeGreaterThanOrEqual(0);
    expect(number).toBeLessThanOrEqual(100);
  });

});
